name: Test Rust Module

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Rust module tests
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Run standalone test
        uses: dagger/dagger-for-github@v8.4.1
        with:
          verb: call
          module: ./ci
          args: test-standalone
          version: "0.19.10"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Run extra-packages test
        uses: dagger/dagger-for-github@v8.4.1
        with:
          verb: call
          module: ./ci
          args: test-with-extra-packages
          version: "0.19.10"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Run extra-repositories test
        uses: dagger/dagger-for-github@v8.4.1
        with:
          verb: call
          module: ./ci
          args: test-with-extra-repositories
          version: "0.19.10"
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
